name: pygame_env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - libmpdec=4.0.0=h827c3e9_0
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.17=h35632f6_0
  - pip=25.2=pyhc872135_0
  - python=3.13.7=h260b955_100_cp313
  - python_abi=3.13=1_cp313
  - setuptools=78.1.1=py313haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py313haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - asttokens==3.0.0
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - decorator==5.2.1
      - executing==2.2.1
      - filelock==3.19.1
      - fonttools==4.60.0
      - fsspec==2025.9.0
      - ipython==9.5.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==3.0.2
      - matplotlib==3.10.6
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.3.3
      - packaging==25.0
      - parso==0.8.5
      - pillow==11.3.0
      - prompt-toolkit==3.0.52
      - pure-eval==0.2.3
      - pygame==2.6.1
      - pygments==2.19.2
      - pyparsing==3.2.4
      - python-dateutil==2.9.0.post0
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - torch==2.8.0
      - torchvision==0.23.0
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - wcwidth==0.2.13
prefix: C:\Users\hussa\anaconda3\envs\pygame_env
